[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = "1.40.0"
serde = "1.0.209"
log = "0.4.22"
env_logger = "0.11.5"
tokio-postgres = "0.7.11"
chrono = "0.4.38"
serde_json = "1.0.128"
json-web-token = "0.2.0"