version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: rust_todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
